FROM openjdk:8-jdk-alpine
MAINTAINER rishank
COPY build/libs/research-survey-extractor-api-1.0.jar research-survey-extractor-api-1.0.jar
ENTRYPOINT ["java","-jar","/research-survey-extractor-api-1.0.jar"]