version: '2'

services:
  research_survey_automator_api:
    image: 'research-survey-extractor-api:latest'
    build:
      context: .
    container_name: research_survey_automator_api
    depends_on:
      - research_survey_automator_db
    ports:
      - 9090:8080
    environment:
      - SPRING_DATASOURCE_HOST=research_survey_automator_db
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  research_survey_automator_db:
    image: 'postgres:13.1-alpine'
    container_name: research_survey_automator_db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      - POSTGRES_DB=research_survey_automator_db

